language: android
jdk: oraclejdk8
sudo: false
os:
  - linux

android:
  components:
    # build components
    #- tools
    - build-tools-26.0.2
    #- platform-tools
    # additional components to emulator device
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
    - android-22
  
  licenses:
    - 'android-sdk-license-.+'

env:
  global:
   # lengthen the install timeout to 8 minutes vs default 2
    - ADB_INSTALL_TIMEOUT=8
    - BT=${ANDROID_HOME}/build-tools/26.0.2
    - APK_DIR=app/build/outputs/apk/release
    - APK_NAME=app-release-unsigned.apk
    - FINAL_APK=dont-panic.apk
    - UGUUSH_DIR=/opt/uguush
    - UGUUSH_BIN=/opt/uguush/uguush

before_install:
  - echo "${ANDROID_HOME}"
  - cp -r DontPanicEducational/licenses ${ANDROID_HOME}/

before_script: 
  # get gradle builder ready
  - cd DontPanicEducational
  - chmod +x ./gradlew
  # Emulator Management: Create, Start and Wait
  # - android list sdk --extended --no-ui --all
  # - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-22,sys-img-x86_64-android-22
  # - android list target
  # - echo "n" | android create avd --force -n test -t android-22 --abi x86_64
  # - emulator -avd test -no-skin -no-audio -no-window &
  # - android-wait-for-emulator
  # - adb shell input keyevent 82 &

script:
  - ./gradlew assembleRelease

after_success:
  - git clone https://github.com/jschx/uguush.git ${UGUUSH_DIR} && chmod +x ${UGUUSH_BIN}
  - ${BT}/zipalign -v -p 4 ${APK_DIR}/${APK_NAME} ${APK_NAME}
  - ${BT}/apksigner sign -v --ks ../dpk --ks-pass env:KEY_PASS --out ${FINAL_APK} ${APK_NAME}
  - ${BT}/apksigner verify -v ${FINAL_APK}
  - ${UGUUSH_BIN} -o teknik -u ${FINAL_APK}

notifications:
  slack: 
    rooms:
      - bleachboys:xo7cosUubMzuwfZFVVEncJ94
    on_success: change # default: always
    on_failure: always # default: always
    on_pull_requests: true
    template:
      - "%{repository_name} by %{author} in branch %{branch}"
      - "Build #%{build_number} has %{result} in %{elapsed_time}"
      - "Commit: %{message}"
