sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - docker build -t tcarrio/panicd:travis .
  - docker pull mongo
  - docker run --name mongodb -d mongo
  - docker run -p 3000:3000 -d --name panicd --link mongodb tcarrio/panicd:travis

# after_success:
#   - echo "$TRAVIS_BRANCH"
#   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#   - docker push tcarrio/panicd:$TRAVIS_BRANCH