language: android
jdk: oraclejdk8
sudo: false
os:
  - linux

android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
  
  licenses:
    - 'android-sdk-license-.+'


before_install:
  - echo "$ANDROID_HOME"
  - cp -r DontPanicEducational/licenses $ANDROID_HOME/

before_script: 
  - cd DontPanicEducational
  - chmod +x ./gradlew
  